name: test docker actions
on: [workflow_dispatch]

jobs:
  my_docker_job:
    runs-on:
        ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: echo 'running docker container...'
      - uses: './'
        with: 
          who-to-greet: jnus
          
      
        
      
      
